--- a/_config.yml
+++ b/_config.yml
@@ -10,13 +10,17 @@
 # in the templates via {{ site.myvariable }}.
 
 title: Your awesome title
-email: your-email@example.com
+email: nathan@example.com
 description: >- # this means to ignore newlines until "baseurl:"
   Write an awesome description for your new site here. You can edit this
   line in _config.yml. It will appear in your document head meta (for
   Google search results) and in your feed.xml site description.
-baseurl: "" # the subpath of your site, e.g. /blog
-url: "" # the base hostname & protocol for your site, e.g. http://example.com
+
+baseurl: "/inconsistentlyfunctional" # the subpath of your site
+url: "https://nathanperry803.github.io" # the base hostname & protocol for your site
+permalink: "/:title/" # Fix for 404 errors on posts
+
+# Social media settings
 twitter_username: jekyllrb
 github_username:  jekyll
 
@@ -24,7 +28,10 @@
 theme: minima
 plugins:
   - jekyll-feed
+  - jekyll-clean-blog
+  - jekyll-sitemap
+  - jekyll-mentions
+  - jekyll-paginate
 
 # Exclude from processing.
 # The following items will not be processed, by default.

# --- Gemfile ---
# Add this line to your Gemfile to enable the new theme
# This will be in the same directory as your _config.yml file
gem "jekyll-clean-blog"
